### ISSUE TITLE
css media query hiba

### ISSUE THREAD

**Issue by gorcsvra** [rrd108/javascript-gyorstalpalo#1]
Nekem a css 126-os sorával van gondom, a min-width nem működik jól...

**Comment by rrd108** [comment]
Pontosabban mi a hiba? Milyen böngészővel jelentkezik?

**Comment by gorcsvra** [comment]
(Elöljáróban biztos nálam van a hiba)
Chrome-ot használok, de próbáltam firefox-al is. Csak mobilnézet jelenik meg:
[https://js-gyorstalpalo.netlify.app/](url)

**Comment by rrd108** [comment]
Ha meghívod ezt az oldalt Chrome-ban és ránézel a dev toolsban akkor ezt látod

![Képernyőkép erről: 2021-12-03 10-23-22](https://user-images.githubusercontent.com/3147489/144578312-cf8712aa-e377-42d2-8837-827f45ce3435.png)

![Képernyőkép erről: 2021-12-03 10-23-40](https://user-images.githubusercontent.com/3147489/144578326-02268463-be92-4821-a1f1-f2f10693ba9a.png)

A viewport megadásánál van valami gondod.

**Comment by gorcsvra** [comment]
Szétcincáltam a viewportot a html-ben. Ezt kijavítottam. Megnéztem dev tools-ban és most nincs hiba. Már csak egy gondom van: még mindig csak mobilnézetet látok..[https://js-gyorstalpalo.netlify.app/](url)

**Comment by rrd108** [comment]
Jelenleg csak egy terméket jelenítesz meg és a css szerint ha a viewport nagyobb mint 640px akkor egy termék 30%-ot foglal el. Ha beteszel plusz termékeket akkor azok szépen mellé kerülnek desktopon, mobil nézetben pedig alá.

**Comment by gorcsvra** [comment]
Köszi, így már értem.

**Comment by rrd108** [comment]
szuper, sok sikert!
