### ISSUE TITLE
kérdés CSS-el kapcsolatban

### ISSUE THREAD

**Issue by gorcsvra** [rrd108/javascript-gyorstalpalo#2]
Bocs nem hiszem,hogy erre való ez az issue rovat, de 22h tájban elkezdett gyötörni egy kérdés CSS-el kapcsolatban. Szóval azt sejtem, hogy  display griddel meg lehet csinálni egy reszponzív oldalt @media nélkül (ezt most próbálom gyakorolni,ha már így eszembe ötlött), de flex-el is meg lehetne így csinálni? És egyáltalán érdemes erre törekedni?

**Comment by rrd108** [comment]
Lehet persze. Hogy érdemes-e az már más kérdés.
Én ezzel úgy vagyok, hogy ha nincs céges policy amihez igazodni kell, akkor csináld úgy ahogy neked könnyebben érthető, mert úgy lesz fentartható.
